### ISSUE TITLE
官方對翻譯不正的回覆

### ISSUE THREAD

**Issue by iyotetsuya** [codebayin/Armello.zh_TW#8]
http://leagueofgeeks.com/forums/index.php?PHPSESSID=125dca7530b9a92a1521d51c8d8422ad&topic=1786.0
在論壇上是有人提起此問題，
看起來翻譯內容是外包交由其它公司處理的。

之前看到他們有提過團隊成員只有八人（含程式外人員）的情況下，
應該沒有能力自行檢測品質。

也許在完成時可以回饋回去，
讓其它平台（像PS4…）的中文使用者也可以不用忍受目前糟糕的翻譯品質。

**Comment by nickexe** [comment]
嗯，這個等翻譯完成之後再說
